// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PeakFit - Transforme Seu Corpo e Alcance Seus Objetivos",
  description: "Plataforma completa de fitness com treinos personalizados, planos alimentares e acompanhamento profissional. Emagrecimento, ganho de massa muscular e resistência.",
  keywords: "fitness, treino personalizado, emagrecimento, ganho de massa, musculação, academia, nutrição, dieta",
  authors: [{ name: "PeakFit" }],
  openGraph: {
    title: "PeakFit - Transforme Seu Corpo",
    description: "Plataforma completa de fitness com treinos personalizados e planos alimentares",
    type: "website",
    locale: "pt_BR",
  },
  robots: {
    index: true,
    follow: true,
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <meta name="theme-color" content="#10b981" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
